services:
  data_base:
    container_name: data_base
    image: postgres:14.1-alpine
    restart: unless-stopped
    volumes:
      - ./data_base/:/var/lib/postgresql/data
    environment:
      - PGDATA="/var/lib/postgresql/pgdata"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432


  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - .env
    command: bash -c "uvicorn main:app --reload --workers 4 --host 0.0.0.0 --port 8000"
    expose:
      - 8000
    # Для отладки системы, оставляю порты 8000 открыты 
    ports:
      - 8000:8000
    depends_on:
      - data_base
    volumes:
      - ./backend:/api

  # frontend:
  #   build: ./frontend
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      # - frontend
      - backend