services:
  data_base:
    container_name: data_base
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - ./data_base/:/var/lib/postgresql/data
    environment:
      - PGDATA="/var/lib/postgresql/pgdata"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432


  backend:
    build: ./backend
    env_file:
      - .env
    command: bash -c "uvicorn main:app --reload --workers 4 --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    depends_on:
      - data_base
    volumes:
      - ./backend:/backend

